/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Configuration */
        get: operations["read_configuration_api_v1_config_get"];
        /** Write Configuration */
        put: operations["write_configuration_api_v1_config_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/league-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Profiles */
        get: operations["read_profiles_api_v1_league_profiles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/league-profiles/samples/entropy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Entropy Sample */
        post: operations["import_entropy_sample_api_v1_league_profiles_samples_entropy_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AppConfiguration */
        AppConfiguration: {
            /** Active League Season Id */
            active_league_season_id: string | null;
            backups: components["schemas"]["BackupConfiguration"];
            display: components["schemas"]["DisplayConfiguration"];
            safety: components["schemas"]["SafetyConfiguration"];
            /**
             * Schema Version
             * @constant
             */
            schema_version: 1;
        };
        /** BackupConfiguration */
        BackupConfiguration: {
            /** Automatic */
            automatic: boolean;
            /** Retention Count */
            retention_count: number;
        };
        /** DisplayConfiguration */
        DisplayConfiguration: {
            /** Reduced Motion */
            reduced_motion: boolean;
            /**
             * Theme
             * @enum {string}
             */
            theme: "system" | "light" | "dark";
            /** Timezone */
            timezone: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** App Version */
            app_version: string;
            /** Database Schema Version */
            database_schema_version: string;
            /** Status */
            status: string;
        };
        /** LeagueProfileSummary */
        LeagueProfileSummary: {
            /** Id */
            id: string;
            /** Imported At */
            imported_at: string;
            /** League Type */
            league_type: string;
            /** Name */
            name: string;
            /** Profile Id */
            profile_id: string;
            /** Sanitized */
            sanitized: boolean;
            /** Season */
            season: number;
            /** Team Count */
            team_count: number;
        };
        /** SafetyConfiguration */
        SafetyConfiguration: {
            /** Confirm Delete */
            confirm_delete: boolean;
            /** Confirm Reset */
            confirm_reset: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_configuration_api_v1_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppConfiguration"];
                };
            };
        };
    };
    write_configuration_api_v1_config_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppConfiguration"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppConfiguration"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    read_profiles_api_v1_league_profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeagueProfileSummary"][];
                };
            };
        };
    };
    import_entropy_sample_api_v1_league_profiles_samples_entropy_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeagueProfileSummary"];
                };
            };
        };
    };
}
