/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/boards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Personal Boards */
        get: operations["list_personal_boards_api_v1_boards_get"];
        put?: never;
        /** Create Personal Board */
        post: operations["create_personal_board_api_v1_boards_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/boards/{board_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Personal Board */
        get: operations["get_personal_board_api_v1_boards__board_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Personal Board */
        patch: operations["update_personal_board_api_v1_boards__board_id__patch"];
        trace?: never;
    };
    "/api/v1/boards/{board_id}/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Board Entry */
        post: operations["create_board_entry_api_v1_boards__board_id__entries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/boards/{board_id}/entries/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Board Entry */
        delete: operations["delete_board_entry_api_v1_boards__board_id__entries__entry_id__delete"];
        options?: never;
        head?: never;
        /** Update Board Entry */
        patch: operations["update_board_entry_api_v1_boards__board_id__entries__entry_id__patch"];
        trace?: never;
    };
    "/api/v1/boards/{board_id}/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Personal Board */
        get: operations["download_personal_board_api_v1_boards__board_id__export_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/boards/{board_id}/gut-elo-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Board Gut Elo Sessions */
        get: operations["list_board_gut_elo_sessions_api_v1_boards__board_id__gut_elo_sessions_get"];
        put?: never;
        /** Create Board Gut Elo Session */
        post: operations["create_board_gut_elo_session_api_v1_boards__board_id__gut_elo_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/boards/{board_id}/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save Board Order */
        put: operations["save_board_order_api_v1_boards__board_id__order_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/boards/{board_id}/tiers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Board Tier */
        post: operations["create_board_tier_api_v1_boards__board_id__tiers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/boards/{board_id}/tiers/{tier_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Board Tier */
        delete: operations["delete_board_tier_api_v1_boards__board_id__tiers__tier_id__delete"];
        options?: never;
        head?: never;
        /** Update Board Tier */
        patch: operations["update_board_tier_api_v1_boards__board_id__tiers__tier_id__patch"];
        trace?: never;
    };
    "/api/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Configuration */
        get: operations["read_configuration_api_v1_config_get"];
        /** Write Configuration */
        put: operations["write_configuration_api_v1_config_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gut-elo-sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Gut Elo Session */
        get: operations["get_gut_elo_session_api_v1_gut_elo_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Gut Elo Session */
        patch: operations["update_gut_elo_session_api_v1_gut_elo_sessions__session_id__patch"];
        trace?: never;
    };
    "/api/v1/gut-elo-sessions/{session_id}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Gut Elo Action */
        post: operations["create_gut_elo_action_api_v1_gut_elo_sessions__session_id__actions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gut-elo-sessions/{session_id}/undo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Undo Gut Elo Action */
        post: operations["undo_gut_elo_action_api_v1_gut_elo_sessions__session_id__undo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/league-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Profiles */
        get: operations["read_profiles_api_v1_league_profiles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/league-profiles/samples/entropy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Entropy Sample */
        post: operations["import_entropy_sample_api_v1_league_profiles_samples_entropy_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/player-imports/csv/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Player Csv */
        post: operations["preview_player_csv_api_v1_player_imports_csv_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/player-imports/fixture/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Fixture */
        post: operations["preview_fixture_api_v1_player_imports_fixture_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/player-imports/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Player Import */
        get: operations["get_player_import_api_v1_player_imports__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/player-imports/{session_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Player Import */
        post: operations["cancel_player_import_api_v1_player_imports__session_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/player-imports/{session_id}/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Commit Player Import */
        post: operations["commit_player_import_api_v1_player_imports__session_id__commit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/player-imports/{session_id}/rows/{row_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save Player Import Decision */
        put: operations["save_player_import_decision_api_v1_player_imports__session_id__rows__row_id__decision_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Canonical Players */
        get: operations["list_canonical_players_api_v1_players_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/players/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Players Csv */
        get: operations["download_players_csv_api_v1_players_export_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/players/{player_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Canonical Player */
        get: operations["get_canonical_player_api_v1_players__player_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Canonical Player */
        patch: operations["update_canonical_player_api_v1_players__player_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AppConfiguration */
        AppConfiguration: {
            /** Active League Season Id */
            active_league_season_id: string | null;
            backups: components["schemas"]["BackupConfiguration"];
            display: components["schemas"]["DisplayConfiguration"];
            safety: components["schemas"]["SafetyConfiguration"];
            /**
             * Schema Version
             * @constant
             */
            schema_version: 1;
        };
        /** BackupConfiguration */
        BackupConfiguration: {
            /** Automatic */
            automatic: boolean;
            /** Retention Count */
            retention_count: number;
        };
        /** BoardCreate */
        BoardCreate: {
            /** Description */
            description?: string | null;
            /** League Profile Id */
            league_profile_id?: string | null;
            /** Name */
            name: string;
            /**
             * Scope
             * @default overall
             * @enum {string}
             */
            scope: "overall" | "rookie" | "veteran";
        };
        /** BoardEntryCreate */
        BoardEntryCreate: {
            /** Player Id */
            player_id: string;
        };
        /** BoardEntryPatch */
        BoardEntryPatch: {
            /** Favorite */
            favorite?: boolean | null;
            /** Note */
            note?: string | null;
            /** Tier Id */
            tier_id?: string | null;
        };
        /** BoardEntryRead */
        BoardEntryRead: {
            /** Favorite */
            favorite: boolean;
            /** Id */
            id: string;
            /** Note */
            note: string | null;
            player: components["schemas"]["PlayerRead"];
            /** Rank */
            rank: number;
            /** Tier Id */
            tier_id: string | null;
            /** Updated At */
            updated_at: string;
        };
        /** BoardListResponse */
        BoardListResponse: {
            /** Items */
            items: components["schemas"]["BoardSummary"][];
        };
        /** BoardOrderUpdate */
        BoardOrderUpdate: {
            /** Player Ids */
            player_ids: string[];
        };
        /** BoardPatch */
        BoardPatch: {
            /** Archived */
            archived?: boolean | null;
            /** Description */
            description?: string | null;
            /** League Profile Id */
            league_profile_id?: string | null;
            /** Name */
            name?: string | null;
            /** Scope */
            scope?: ("overall" | "rookie" | "veteran") | null;
        };
        /** BoardRead */
        BoardRead: {
            /** Archived */
            archived: boolean;
            /** Created At */
            created_at: string;
            /** Description */
            description: string | null;
            /** Entries */
            entries: components["schemas"]["BoardEntryRead"][];
            /** Entry Count */
            entry_count: number;
            /** Id */
            id: string;
            /** League Profile Id */
            league_profile_id: string | null;
            /** Name */
            name: string;
            /**
             * Scope
             * @enum {string}
             */
            scope: "overall" | "rookie" | "veteran";
            /** Tiers */
            tiers: components["schemas"]["BoardTierRead"][];
            /** Updated At */
            updated_at: string;
        };
        /** BoardSummary */
        BoardSummary: {
            /** Archived */
            archived: boolean;
            /** Created At */
            created_at: string;
            /** Description */
            description: string | null;
            /** Entry Count */
            entry_count: number;
            /** Id */
            id: string;
            /** League Profile Id */
            league_profile_id: string | null;
            /** Name */
            name: string;
            /**
             * Scope
             * @enum {string}
             */
            scope: "overall" | "rookie" | "veteran";
            /** Updated At */
            updated_at: string;
        };
        /** BoardTierCreate */
        BoardTierCreate: {
            /** Color */
            color?: string | null;
            /** Name */
            name: string;
            /** Tier Order */
            tier_order?: number | null;
        };
        /** BoardTierPatch */
        BoardTierPatch: {
            /** Color */
            color?: string | null;
            /** Name */
            name?: string | null;
            /** Tier Order */
            tier_order?: number | null;
        };
        /** BoardTierRead */
        BoardTierRead: {
            /** Color */
            color: string | null;
            /** Created At */
            created_at: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Tier Order */
            tier_order: number;
            /** Updated At */
            updated_at: string;
        };
        /** CsvPreviewRequest */
        CsvPreviewRequest: {
            /** Csv Text */
            csv_text: string;
            /**
             * Filename
             * @default players.csv
             */
            filename: string;
        };
        /** DisplayConfiguration */
        DisplayConfiguration: {
            /** Reduced Motion */
            reduced_motion: boolean;
            /**
             * Theme
             * @enum {string}
             */
            theme: "system" | "light" | "dark";
            /** Timezone */
            timezone: string;
        };
        /** GutEloActionCreate */
        GutEloActionCreate: {
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "a_win" | "b_win" | "insufficient" | "skip";
            /** Player A Id */
            player_a_id: string;
            /** Player B Id */
            player_b_id: string;
            /** Revision */
            revision: number;
        };
        /** GutEloActionRead */
        GutEloActionRead: {
            /** Created At */
            created_at: string;
            /** Id */
            id: string;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "a_win" | "b_win" | "insufficient" | "skip";
            /** Player A Id */
            player_a_id: string;
            /** Player B Id */
            player_b_id: string;
            /** Sequence Number */
            sequence_number: number;
        };
        /** GutEloPairRead */
        GutEloPairRead: {
            player_a: components["schemas"]["PlayerRead"];
            player_b: components["schemas"]["PlayerRead"];
            /** Revision */
            revision: number;
        };
        /** GutEloParticipantRead */
        GutEloParticipantRead: {
            /** Decisive Count */
            decisive_count: number;
            /** Gut Rank */
            gut_rank: number;
            player: components["schemas"]["PlayerRead"];
            /** Rating */
            rating: number;
            /** Starting Manual Rank */
            starting_manual_rank: number;
            /** Starting Tier Name */
            starting_tier_name: string | null;
        };
        /** GutEloProgressRead */
        GutEloProgressRead: {
            /** Coverage Percent */
            coverage_percent: number;
            /** Decisive Count */
            decisive_count: number;
            /** Insufficient Count */
            insufficient_count: number;
            /** Participant Count */
            participant_count: number;
            /** Participants With Decision */
            participants_with_decision: number;
            /** Progress Percent */
            progress_percent: number;
            /** Resolved Count */
            resolved_count: number;
            /** Skip Count */
            skip_count: number;
            /** Stability Explanation */
            stability_explanation: string;
            /**
             * Stability Label
             * @enum {string}
             */
            stability_label: "starting" | "developing" | "useful_signal" | "still_moving";
            /** Target Count */
            target_count: number;
        };
        /** GutEloSessionCreate */
        GutEloSessionCreate: {
            /** Position */
            position?: ("QB" | "RB" | "WR" | "TE" | "K" | "DEF" | "UNKNOWN") | null;
            /**
             * Queue Mode
             * @default board
             * @enum {string}
             */
            queue_mode: "board" | "position" | "tier" | "uncertainty";
            /** Target Count */
            target_count?: number | null;
            /** Tier Id */
            tier_id?: string | null;
        };
        /** GutEloSessionListResponse */
        GutEloSessionListResponse: {
            /** Items */
            items: components["schemas"]["GutEloSessionSummary"][];
        };
        /** GutEloSessionPatch */
        GutEloSessionPatch: {
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "paused";
        };
        /** GutEloSessionRead */
        GutEloSessionRead: {
            /** Actions */
            actions: components["schemas"]["GutEloActionRead"][];
            /** Board Id */
            board_id: string;
            /** Board Name */
            board_name: string;
            /**
             * Board Scope
             * @enum {string}
             */
            board_scope: "overall" | "rookie" | "veteran";
            /** Completed At */
            completed_at: string | null;
            /** Created At */
            created_at: string;
            /** Id */
            id: string;
            /**
             * Manual Board Unchanged
             * @default true
             * @constant
             */
            manual_board_unchanged: true;
            next_pair: components["schemas"]["GutEloPairRead"] | null;
            /** Participant Count */
            participant_count: number;
            /** Participants */
            participants: components["schemas"]["GutEloParticipantRead"][];
            /** Position */
            position: ("QB" | "RB" | "WR" | "TE" | "K" | "DEF" | "UNKNOWN") | null;
            progress: components["schemas"]["GutEloProgressRead"];
            /**
             * Queue Mode
             * @enum {string}
             */
            queue_mode: "board" | "position" | "tier" | "uncertainty";
            /** Resolved Count */
            resolved_count: number;
            /** Revision */
            revision: number;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "paused" | "completed";
            /** Target Count */
            target_count: number;
            /** Tier Id */
            tier_id: string | null;
            /** Updated At */
            updated_at: string;
        };
        /** GutEloSessionSummary */
        GutEloSessionSummary: {
            /** Board Id */
            board_id: string;
            /** Board Name */
            board_name: string;
            /**
             * Board Scope
             * @enum {string}
             */
            board_scope: "overall" | "rookie" | "veteran";
            /** Completed At */
            completed_at: string | null;
            /** Created At */
            created_at: string;
            /** Id */
            id: string;
            /** Participant Count */
            participant_count: number;
            /** Position */
            position: ("QB" | "RB" | "WR" | "TE" | "K" | "DEF" | "UNKNOWN") | null;
            /**
             * Queue Mode
             * @enum {string}
             */
            queue_mode: "board" | "position" | "tier" | "uncertainty";
            /** Resolved Count */
            resolved_count: number;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "paused" | "completed";
            /** Target Count */
            target_count: number;
            /** Tier Id */
            tier_id: string | null;
            /** Updated At */
            updated_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** App Version */
            app_version: string;
            /** Database Schema Version */
            database_schema_version: string;
            /** Status */
            status: string;
        };
        /** LeagueProfileSummary */
        LeagueProfileSummary: {
            /** Id */
            id: string;
            /** Imported At */
            imported_at: string;
            /** League Type */
            league_type: string;
            /** Name */
            name: string;
            /** Profile Id */
            profile_id: string;
            /** Sanitized */
            sanitized: boolean;
            /** Season */
            season: number;
            /** Team Count */
            team_count: number;
        };
        /** MappingDecisionRequest */
        MappingDecisionRequest: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "match_existing" | "create_new" | "ignore" | "clear";
            /** Note */
            note?: string | null;
            /** Player Id */
            player_id?: string | null;
        };
        /** PlayerCandidate */
        PlayerCandidate: {
            /** Display Name */
            display_name: string;
            /** External Id */
            external_id?: string | null;
            /** Fantasy Positions */
            fantasy_positions: ("QB" | "RB" | "WR" | "TE" | "K" | "DEF" | "UNKNOWN")[];
            /** First Name */
            first_name?: string | null;
            /**
             * Include
             * @default true
             */
            include: boolean;
            /**
             * Is Rookie
             * @default false
             */
            is_rookie: boolean;
            /** Last Name */
            last_name?: string | null;
            /**
             * Primary Position
             * @enum {string}
             */
            primary_position: "QB" | "RB" | "WR" | "TE" | "K" | "DEF" | "UNKNOWN";
            /** Provider */
            provider?: string | null;
            /** Rookie Class */
            rookie_class?: number | null;
            /** Search Name */
            search_name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "inactive" | "injured" | "reserve" | "unknown";
            /** Suffix */
            suffix?: string | null;
            /** Team */
            team?: string | null;
        };
        /** PlayerImportCommitResponse */
        PlayerImportCommitResponse: {
            /** Created Players */
            created_players: number;
            /** Ignored Rows */
            ignored_rows: number;
            session: components["schemas"]["PlayerImportSessionRead"];
            /** Updated Players */
            updated_players: number;
        };
        /** PlayerImportRowRead */
        PlayerImportRowRead: {
            candidate: components["schemas"]["PlayerCandidate"] | null;
            /** Candidate Players */
            candidate_players: components["schemas"]["PlayerRead"][];
            /** Explanation */
            explanation: string;
            /** Id */
            id: string;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "new" | "matched" | "changed" | "ambiguous" | "invalid" | "ignored";
            /** Proposed Player Id */
            proposed_player_id: string | null;
            /** Reason Code */
            reason_code: string;
            /** Resolved Player Id */
            resolved_player_id: string | null;
            /** Row Number */
            row_number: number;
            /** Source Name */
            source_name: string | null;
        };
        /** PlayerImportSessionRead */
        PlayerImportSessionRead: {
            /** Ambiguous Count */
            ambiguous_count: number;
            /** Changed Count */
            changed_count: number;
            /** Committed At */
            committed_at: string | null;
            /** Created At */
            created_at: string;
            /** Filename */
            filename: string | null;
            /** Id */
            id: string;
            /** Ignored Count */
            ignored_count: number;
            /** Invalid Count */
            invalid_count: number;
            /** Matched Count */
            matched_count: number;
            /** New Count */
            new_count: number;
            /** Rows */
            rows: components["schemas"]["PlayerImportRowRead"][];
            /** Source */
            source: string;
            /**
             * Status
             * @enum {string}
             */
            status: "preview" | "committed" | "cancelled" | "failed";
        };
        /** PlayerListResponse */
        PlayerListResponse: {
            /** Items */
            items: components["schemas"]["PlayerRead"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** PlayerPatch */
        PlayerPatch: {
            /** Display Name */
            display_name?: string | null;
            /** Fantasy Positions */
            fantasy_positions?: ("QB" | "RB" | "WR" | "TE" | "K" | "DEF" | "UNKNOWN")[] | null;
            /** Is Rookie */
            is_rookie?: boolean | null;
            /** Primary Position */
            primary_position?: ("QB" | "RB" | "WR" | "TE" | "K" | "DEF" | "UNKNOWN") | null;
            /** Rookie Class */
            rookie_class?: number | null;
            /** Status */
            status?: ("active" | "inactive" | "injured" | "reserve" | "unknown") | null;
            /** Team */
            team?: string | null;
        };
        /** PlayerRead */
        PlayerRead: {
            /** Display Name */
            display_name: string;
            /** Fantasy Positions */
            fantasy_positions: ("QB" | "RB" | "WR" | "TE" | "K" | "DEF" | "UNKNOWN")[];
            /** First Name */
            first_name: string | null;
            /** Id */
            id: string;
            /** Is Rookie */
            is_rookie: boolean;
            /** Last Name */
            last_name: string | null;
            /**
             * Primary Position
             * @enum {string}
             */
            primary_position: "QB" | "RB" | "WR" | "TE" | "K" | "DEF" | "UNKNOWN";
            /** Relevant */
            relevant: boolean;
            /** Rookie Class */
            rookie_class: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "inactive" | "injured" | "reserve" | "unknown";
            /** Suffix */
            suffix: string | null;
            /** Team */
            team: string | null;
            /** Updated At */
            updated_at: string;
        };
        /** SafetyConfiguration */
        SafetyConfiguration: {
            /** Confirm Delete */
            confirm_delete: boolean;
            /** Confirm Reset */
            confirm_reset: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_personal_boards_api_v1_boards_get: {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_personal_board_api_v1_boards_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BoardCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_personal_board_api_v1_boards__board_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                board_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_personal_board_api_v1_boards__board_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                board_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BoardPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_board_entry_api_v1_boards__board_id__entries_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                board_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BoardEntryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_board_entry_api_v1_boards__board_id__entries__entry_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                board_id: string;
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_board_entry_api_v1_boards__board_id__entries__entry_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                board_id: string;
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BoardEntryPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_personal_board_api_v1_boards__board_id__export_csv_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                board_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_board_gut_elo_sessions_api_v1_boards__board_id__gut_elo_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                board_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GutEloSessionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_board_gut_elo_session_api_v1_boards__board_id__gut_elo_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                board_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GutEloSessionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GutEloSessionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_board_order_api_v1_boards__board_id__order_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                board_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BoardOrderUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_board_tier_api_v1_boards__board_id__tiers_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                board_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BoardTierCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_board_tier_api_v1_boards__board_id__tiers__tier_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                board_id: string;
                tier_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_board_tier_api_v1_boards__board_id__tiers__tier_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                board_id: string;
                tier_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BoardTierPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_configuration_api_v1_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppConfiguration"];
                };
            };
        };
    };
    write_configuration_api_v1_config_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppConfiguration"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppConfiguration"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_gut_elo_session_api_v1_gut_elo_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GutEloSessionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_gut_elo_session_api_v1_gut_elo_sessions__session_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GutEloSessionPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GutEloSessionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_gut_elo_action_api_v1_gut_elo_sessions__session_id__actions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GutEloActionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GutEloSessionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    undo_gut_elo_action_api_v1_gut_elo_sessions__session_id__undo_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GutEloSessionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    read_profiles_api_v1_league_profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeagueProfileSummary"][];
                };
            };
        };
    };
    import_entropy_sample_api_v1_league_profiles_samples_entropy_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeagueProfileSummary"];
                };
            };
        };
    };
    preview_player_csv_api_v1_player_imports_csv_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CsvPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerImportSessionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_fixture_api_v1_player_imports_fixture_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerImportSessionRead"];
                };
            };
        };
    };
    get_player_import_api_v1_player_imports__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerImportSessionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_player_import_api_v1_player_imports__session_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerImportSessionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    commit_player_import_api_v1_player_imports__session_id__commit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerImportCommitResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_player_import_decision_api_v1_player_imports__session_id__rows__row_id__decision_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                row_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MappingDecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerImportSessionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_canonical_players_api_v1_players_get: {
        parameters: {
            query?: {
                search?: string | null;
                position?: ("QB" | "RB" | "WR" | "TE" | "K" | "DEF" | "UNKNOWN") | null;
                status?: ("active" | "inactive" | "injured" | "reserve" | "unknown") | null;
                rookie_class?: number | null;
                relevant_only?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_players_csv_api_v1_players_export_csv_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_canonical_player_api_v1_players__player_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_canonical_player_api_v1_players__player_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayerPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
